CREATE TABLE `products`
(
    `sku`          VARCHAR(100) NOT NULL PRIMARY KEY,
    `content_data` MEDIUMBLOB   NOT NULL,
    `created_at`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);